global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'jenkins-rollback-webhook' # Must match specified receiver name exactly

receivers:
  - name: 'jenkins-rollback-webhook' # Must match specified receiver name exactly
    webhook_configs:
      - url: 'http://54.163.118.202:8080/generic-webhook-trigger/invoke?token=ROLLBACK_83AB79_TOKEN'
        http_config:
          basic_auth:
            username: 'abdullah'
            password: '113a57e0ce3f495cc0363b9eba599a5634'
