apiVersion: v1
kind: Service
metadata:
  name: sentiment-api
spec:
  selector:
    app: sentiment-api
    slot: green
  ports:
    - protocol: TCP
      port: 32500
      targetPort: 5000
  type: LoadBalancer
